<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./assets/asteroid.glb
-->

<script lang="ts">
  import { T, type Props } from "@threlte/core";
  import { useGltf } from "@threlte/extras";
  import type { Group } from "three";

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<typeof Group> = $props();

  const gltf = useGltf("/assets/asteroid.glb");
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Asteroid_2c.geometry}
      material={gltf.materials.Asteroid2c}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
