<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./assets/sun2.glb
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sun-9ef1c68fbb944147bcfcc891d3912645
Title: Sun
-->

<script lang="ts">
  import { Group } from "three";

  import { T } from "@threlte/core";
  import { useGltf, useGltfAnimations } from "@threlte/extras";
  import type { Props } from "@threlte/core";

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: {
    fallback?: any;
    error?: any;
    ref?: any;
    children?: any;
  } & Props<typeof Group> = $props();

  ref = new Group();

  const gltf = useGltf("/assets/sun.glb");

  export const { actions, mixer } = useGltfAnimations(gltf, ref);
</script>

<T is={ref} dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group
          name="3a2aaa22fb3d4b329318a980ad1bf6d1fbx"
          rotation={[Math.PI / 2, 0, 0]}
        >
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group name="UnstableStarCore" rotation={[-Math.PI / 2, 0, 0]}>
                <T.Mesh
                  name="UnstableStarCore_1_0"
                  geometry={gltf.nodes.UnstableStarCore_1_0.geometry}
                  material={gltf.materials.material}
                />
              </T.Group>
              <T.Group
                name="UnstableStarref"
                rotation={[-Math.PI / 2, 0, 0]}
                scale={1.01}
              >
                <T.Mesh
                  name="UnstableStarref_2_0"
                  geometry={gltf.nodes.UnstableStarref_2_0.geometry}
                  material={gltf.materials.material_1}
                />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
